# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: true

# favicon
favicon: /images/my_icon.png

# cover info config
coverTitle: 把时间的钢印砸在这无人问津的角落里

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10

# webmaster info config
avatar: /images/my_icon.png
authorName: Kevin Zhou
authorLink: https://aliaosha.github.io
authorAbout: https://about.tangkunyin.com
authorDesc: 脚踏实地，无欲无求

# your site build time or founded date
siteBuildingTime: 8/3/2017


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   技术: tech
   机器学习: Machine Learning
   人文: humanity
   资源: resource

categories: active
# Independent page of uri config
about: /about
links: /friendlinks
feedback: /feedback
timeline: /timeline

# Social info config
sinaWb: http://weibo.com/u/2004315142
facebook: https://fackbook.com/
github: https://github.com/ALiaoSha


# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=bcace447-fa41-4579-9783-86fdf0f723e2

# MathJax Support
math.mathjax:
  enable: true
  per_page: true
